os: linux
dist: xenial
language: cpp
sudo: enabled

install:
  - export ROOTDIR=`pwd`
  - sudo apt-get update
  - sudo apt-get install -y gcc gfortran cmake wget liblapack-dev
  - sudo apt-get install -y libopenmpi-dev openmpi-bin
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y enchant
  - |
    sudo apt-get install -y texlive-latex-recommended texlive-latex-extra \
         texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra latexmk
  - kanji-config-updmap-sys ipaex
  - pyenv global 3.7.1
  - pip3 install -U pip
script:
  - cd ${ROOTDIR}
  - mkdir build
  - cd build
  - cmake -DDocument=ON ../
  - VERBOSE=1 make
  - export OMP_NUM_THREADS=1
  - ctest -VV
after_success:
  - cd ${ROOTDIR}
  - /bin/bash -x ${ROOTDIR}/.travis_scripts/deploy_docs.sh
