matrix:
  include:
  - language: cpp
    sudo: enabled
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gcc liblapack-dev cmake
      - pip install numpy --user
    install:
      - mkdir build
      - cd build
    script:
      - cmake ../
#      - make
#      - export OMP_NUM_THREADS=1
#      - make test
#      - rm -r test
#      - make
#      - export OMP_NUM_THREADS=3
#      - make test
#      - rm -r *
      - sudo apt-get install -y libopenmpi-dev openmpi-bin
      - cmake ../
      - make
      - export OMP_NUM_THREADS=1
      - make test MPIRUN="mpiexec -np 4"
      - rm -r test
      - make
      - export OMP_NUM_THREADS=3
      - make test MPIRUN="mpiexec -np 4"
#  - os: osx
#    language: cpp
#    sudo: enabled
#    before_install:
#      - brew update
#      - brew install gcc || true
#      - brew link --overwrite gcc
#      - brew install lapack
#    install:
#      - mkdir build
#      - cd build
#    script:
#      - cmake ../
#      - make
#      - export OMP_NUM_THREADS=1
#      - make test
