matrix:
  include:
  - language: cpp
    sudo: enabled
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gcc gfortran liblapack-dev cmake
      - sudo apt-get install -y libopenmpi-dev openmpi-bin
    install:
      - mkdir build
      - cd build
      - cmake ../
      - VERBOSE=1 make 
    script:
      - export OMP_NUM_THREADS=1
      - make test ARGS='-V'
 
