name: deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Prepare LaTeX env
      run: |
        sudo apt install \
          texlive-latex-recommended texlive-latex-extra \
          texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra latexmk
        kanji-config-updmap-sys ipaex

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinxcontrib-spelling

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        cmake -E make_directory build
        cd build
        cmake -DDocument=ON ../
        make doc
